# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderers
    Domain: consensus.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: PeersA
    Domain: blockchain-a.com
    # ---------------------------------------------------------------------------
    # "Specs"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of hosts in your
    # configuration.  Most users will want to use Template, below
    #
    # Specs is an array of Spec entries.  Each Spec entry consists of two fields:
    #   - Hostname:   (Required) The desired hostname, sans the domain.
    #   - CommonName: (Optional) Specifies the template or explicit override for
    #                 the CN.  By default, this is the template:
    #
    #                              "{{.Hostname}}.{{.Domain}}"
    #
    #                 which obtains its values from the Spec.Hostname and
    #                 Org.Domain, respectively.
    # ---------------------------------------------------------------------------
    # Specs:
    #   - Hostname: foo # implicitly "foo.org1.example.com"
    #     CommonName: foo27.org5.example.com # overrides Hostname-based FQDN set above
    #   - Hostname: bar
    #   - Hostname: baz
    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    #
    # Note: Template and Specs are not mutually exclusive.  You may define both
    # sections and the aggregate nodes will be created for you.  Take care with
    # name collisions
    # ---------------------------------------------------------------------------
    Template:
      Count: 1
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 1

  - Name: PeersB
    Domain: blockchain-b.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersC
    Domain: blockchain-c.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersD
    Domain: blockchain-d.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersE
    Domain: blockchain-e.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersF
    Domain: blockchain-f.com
    Template:
      Count: 1
    Users:
      Count: 1


  - Name: PeersG
    Domain: blockchain-g.com
    Template:
      Count: 1
    Users:
      Count: 1


  - Name: PeersH
    Domain: blockchain-h.com
    Template:
      Count: 1
    Users:
      Count: 1


  - Name: PeersI
    Domain: blockchain-i.com
    Template:
      Count: 1
    Users:
      Count: 1


  - Name: PeersJ
    Domain: blockchain-j.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersK
    Domain: blockchain-k.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersL
    Domain: blockchain-l.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersM
    Domain: blockchain-m.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersN
    Domain: blockchain-n.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersO
    Domain: blockchain-o.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersP
    Domain: blockchain-p.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersQ
    Domain: blockchain-q.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersR
    Domain: blockchain-r.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: PeersS
    Domain: blockchain-s.com
    Template:
      Count: 1
    Users:
      Count: 1


  - Name: PeersT
    Domain: blockchain-t.com
    Template:
      Count: 1
    Users:
      Count: 1
