# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer0.fgodinho.com:
  orderer1.fgodinho.com:
  peer0.fgodinho.com:
  peer1.fgodinho.com:
  peer2.fgodinho.com:
  peer3.fgodinho.com:
  peer4.fgodinho.com:
  peer5.fgodinho.com:

networks:
  bootstrap:

services:

  zookeeper0:
    container_name: zookeeper0
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - bootstrap

  zookeeper1:
    container_name: zookeeper1
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 3181:2181
      - 4888:2888
      - 5888:3888
    networks:
      - bootstrap

  zookeeper2:
    container_name: zookeeper2
    image: hyperledger/fabric-zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 4181:2181
      - 6888:2888
      - 7888:3888
    networks:
      - bootstrap

  kafka0:
    image: hyperledger/fabric-kafka
    container_name: kafka0
    environment:
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 9092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    links:
      - zookeeper0:zookeeper0
      - zookeeper1:zookeeper1
      - zookeeper2:zookeeper2
    networks:
      - bootstrap

  kafka1:
    image: hyperledger/fabric-kafka
    container_name: kafka1
    environment:
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 10092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    links:
      - zookeeper0:zookeeper0
      - zookeeper1:zookeeper1
      - zookeeper2:zookeeper2
    networks:
      - bootstrap

  kafka2:
    image: hyperledger/fabric-kafka
    container_name: kafka2
    environment:
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 11092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    links:
      - zookeeper0:zookeeper0
      - zookeeper1:zookeeper1
      - zookeeper2:zookeeper2
    networks:
      - bootstrap

  kafka3:
    image: hyperledger/fabric-kafka
    container_name: kafka3
    environment:
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 12092:9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    links:
      - zookeeper0:zookeeper0
      - zookeeper1:zookeeper1
      - zookeeper2:zookeeper2
    networks:
      - bootstrap

  orderer0.fgodinho.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.fgodinho.com
    container_name: orderer0.fgodinho.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    links:
      - kafka0:kafka0
      - kafka1:kafka1
      - kafka2:kafka2
      - kafka3:kafka3
    networks:
      - bootstrap

  orderer1.fgodinho.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.fgodinho.com
    container_name: orderer1.fgodinho.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    links:
      - kafka0:kafka0
      - kafka1:kafka1
      - kafka2:kafka2
      - kafka3:kafka3
    networks:
      - bootstrap

  peer0.fgodinho.com:
    container_name: peer0.fgodinho.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.fgodinho.com
    networks:
      - bootstrap

  peer1.fgodinho.com:
    container_name: peer1.fgodinho.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.fgodinho.com
    networks:
      - bootstrap

  peer2.fgodinho.com:
    container_name: peer2.fgodinho.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.fgodinho.com
    networks:
      - bootstrap

  peer3.fgodinho.com:
    container_name: peer3.fgodinho.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer3.fgodinho.com
    networks:
      - bootstrap

  peer4.fgodinho.com:
    container_name: peer4.fgodinho.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer4.fgodinho.com
    networks:
      - bootstrap

  peer5.fgodinho.com:
    container_name: peer5.fgodinho.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer5.fgodinho.com
    networks:
      - bootstrap

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.fgodinho.com:7051
      - CORE_PEER_LOCALMSPID=PeersMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fgodinho.com/peers/peer0.fgodinho.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fgodinho.com/peers/peer0.fgodinho.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fgodinho.com/peers/peer0.fgodinho.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fgodinho.com/users/Admin@fgodinho.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer0.fgodinho.com
      - orderer1.fgodinho.com
      - peer0.fgodinho.com
      - peer1.fgodinho.com
      - peer2.fgodinho.com
      - peer3.fgodinho.com
      - peer4.fgodinho.com
      - peer5.fgodinho.com
    networks:
      - bootstrap
