# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  osn:

services:

  bft-replica0:
    dns_search: .
    container_name: bft-replica0
    extends:
      file: base/docker-compose-bftsmart-base.yaml
      service: bft-replica
    environment:
      - BFTSMART_REPLICAS=0 bft-replica0 11000,1 bft-replica1 11000,2 bft-replica2 11000,3 bft-replica3 11000
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart
    command: ./startReplica.sh 0
    networks:
      - osn


  bft-replica1:
    dns_search: .
    container_name: bft-replica1
    extends:
      file: base/docker-compose-bftsmart-base.yaml
      service: bft-replica
    environment:
      - BFTSMART_REPLICAS=0 bft-replica0 11000,1 bft-replica1 11000,2 bft-replica2 11000,3 bft-replica3 11000
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart
    command: ./startReplica.sh 1
    networks:
      - osn


  bft-replica2:
    dns_search: .
    container_name: bft-replica2
    extends:
      file: base/docker-compose-bftsmart-base.yaml
      service: bft-replica
    environment:
      - BFTSMART_REPLICAS=0 bft-replica0 11000,1 bft-replica1 11000,2 bft-replica2 11000,3 bft-replica3 11000
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart
    command: ./startReplica.sh 2
    networks:
      - osn

  bft-replica3:
    dns_search: .
    container_name: bft-replica3
    extends:
      file: base/docker-compose-bftsmart-base.yaml
      service: bft-replica
    environment:
      - BFTSMART_REPLICAS=0 bft-replica0 11000,1 bft-replica1 11000,2 bft-replica2 11000,3 bft-replica3 11000
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart
    command: ./startReplica.sh 3
    networks:
      - osn

  orderer0.consensus.com:
    dns_search: .
    environment:
      - BFTSMART_FRONTEND_ID=1000
    command: ./orderer-bftfrontend.sh
    depends_on:
      - bft-replica0
      - bft-replica1
      - bft-replica2
      - bft-replica3

  orderer1.consensus.com:
    dns_search: .
    environment:
      - BFTSMART_FRONTEND_ID=2000
    command: ./orderer-bftfrontend.sh
    depends_on:
      - bft-replica0
      - bft-replica1
      - bft-replica2
      - bft-replica3
