# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.consensus.com:
    container_name: orderer0.consensus.com
    image: fgodinho/gassy-octopus-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_LISTENPORT=7050
      # kafka
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
      - ORDERER_GENERAL_LEDGERTYPE=ram
      # BFTsmart
      - BFTSMART_RECVPORT=9999
      - BFTSMART_CONNECTION_POOL_SIZE=10
      - BFTSMART_REPLICAS=0 bft-replica0 11000,1 bft-replica1 11000,2 bft-replica2 11000,3 bft-replica3 11000
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer0.consensus.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer0.consensus.com/tls/:/var/hyperledger/orderer/tls
    - orderer0.consensus.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer1.consensus.com:
    container_name: orderer1.consensus.com
    image: fgodinho/gassy-octopus-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_LISTENPORT=7050
      # kafka
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
      - ORDERER_GENERAL_LEDGERTYPE=ram
      # BFTsmart
      - BFTSMART_RECVPORT=9999
      - BFTSMART_CONNECTION_POOL_SIZE=10
      - BFTSMART_REPLICAS=0 bft-replica0 11000,1 bft-replica1 11000,2 bft-replica2 11000,3 bft-replica3 11000
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer1.consensus.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer1.consensus.com/tls/:/var/hyperledger/orderer/tls
    - orderer1.consensus.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050


  peer0.blockchain-a.com:
    container_name: peer0.blockchain-a.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-a.com
      - CORE_PEER_ADDRESS=peer0.blockchain-a.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-a.com:7051
      - CORE_PEER_LOCALMSPID=PeersAMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-a.com/peers/peer0.blockchain-a.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-a.com/peers/peer0.blockchain-a.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-a.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.blockchain-b.com:
    container_name: peer0.blockchain-b.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-b.com
      - CORE_PEER_ADDRESS=peer0.blockchain-b.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-b.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.blockchain-b.com:7051
      - CORE_PEER_LOCALMSPID=PeersBMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-b.com/peers/peer0.blockchain-b.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-b.com/peers/peer0.blockchain-b.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-b.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.blockchain-c.com:
    container_name: peer0.blockchain-c.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-c.com
      - CORE_PEER_ADDRESS=peer0.blockchain-c.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-c.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.blockchain-a.com:7051
      - CORE_PEER_LOCALMSPID=PeersCMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-c.com/peers/peer0.blockchain-c.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-c.com/peers/peer0.blockchain-c.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-c.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.blockchain-d.com:
    container_name: peer0.blockchain-d.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-d.com
      - CORE_PEER_ADDRESS=peer0.blockchain-d.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-d.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.blockchain-a.com:7051
      - CORE_PEER_LOCALMSPID=PeersDMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-d.com/peers/peer0.blockchain-d.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-d.com/peers/peer0.blockchain-d.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-d.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053



  peer0.blockchain-e.com:
    container_name: peer0.blockchain-e.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-e.com
      - CORE_PEER_ADDRESS=peer0.blockchain-e.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-e.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.blockchain-b.com:7051
      - CORE_PEER_LOCALMSPID=PeersEMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-e.com/peers/peer0.blockchain-e.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-e.com/peers/peer0.blockchain-e.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-e.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer0.blockchain-f.com:
    container_name: peer0.blockchain-f.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-f.com
      - CORE_PEER_ADDRESS=peer0.blockchain-f.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-f.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.blockchain-b.com:7051
      - CORE_PEER_LOCALMSPID=PeersFMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-f.com/peers/peer0.blockchain-f.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-f.com/peers/peer0.blockchain-f.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-f.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
