# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.fgodinho.com:
    container_name: orderer0.fgodinho.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # kafka
      - ORDERER_GENERAL_LISTENPORT=7050
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
      - ORDERER_GENERAL_LEDGERTYPE=ram
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/fgodinho.com/orderers/orderer0.fgodinho.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/fgodinho.com/orderers/orderer0.fgodinho.com/tls/:/var/hyperledger/orderer/tls
    - orderer0.fgodinho.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer1.fgodinho.com:
    container_name: orderer1.fgodinho.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # kafka
      - ORDERER_GENERAL_LISTENPORT=7050
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092,kafka3:9092]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
      - ORDERER_GENERAL_LEDGERTYPE=ram
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/fgodinho.com/orderers/orderer1.fgodinho.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/fgodinho.com/orderers/orderer1.fgodinho.com/tls/:/var/hyperledger/orderer/tls
    - orderer1.fgodinho.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050


  peer0.fgodinho.com:
    container_name: peer0.fgodinho.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.fgodinho.com
      - CORE_PEER_ADDRESS=peer0.fgodinho.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fgodinho.com:7051
      - CORE_PEER_LOCALMSPID=PeersMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer0.fgodinho.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer0.fgodinho.com/tls:/etc/hyperledger/fabric/tls
        - peer0.fgodinho.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.fgodinho.com:
    container_name: peer1.fgodinho.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.fgodinho.com
      - CORE_PEER_ADDRESS=peer1.fgodinho.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fgodinho.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fgodinho.com:7051
      - CORE_PEER_LOCALMSPID=PeersMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer1.fgodinho.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer1.fgodinho.com/tls:/etc/hyperledger/fabric/tls
        - peer1.fgodinho.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer2.fgodinho.com:
    container_name: peer2.fgodinho.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.fgodinho.com
      - CORE_PEER_ADDRESS=peer2.fgodinho.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.fgodinho.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fgodinho.com:7051
      - CORE_PEER_LOCALMSPID=PeersMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer2.fgodinho.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer2.fgodinho.com/tls:/etc/hyperledger/fabric/tls
        - peer2.fgodinho.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer3.fgodinho.com:
    container_name: peer3.fgodinho.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.fgodinho.com
      - CORE_PEER_ADDRESS=peer3.fgodinho.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.fgodinho.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fgodinho.com:7051
      - CORE_PEER_LOCALMSPID=PeersMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer3.fgodinho.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer3.fgodinho.com/tls:/etc/hyperledger/fabric/tls
        - peer3.fgodinho.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer4.fgodinho.com:
    container_name: peer4.fgodinho.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4.fgodinho.com
      - CORE_PEER_ADDRESS=peer4.fgodinho.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.fgodinho.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fgodinho.com:7051
      - CORE_PEER_LOCALMSPID=PeersMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer4.fgodinho.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer4.fgodinho.com/tls:/etc/hyperledger/fabric/tls
        - peer4.fgodinho.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer5.fgodinho.com:
    container_name: peer5.fgodinho.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer5.fgodinho.com
      - CORE_PEER_ADDRESS=peer5.fgodinho.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.fgodinho.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fgodinho.com:7051
      - CORE_PEER_LOCALMSPID=PeersMSP
    command: peer node start #--peer-chaincodedev=true
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer5.fgodinho.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fgodinho.com/peers/peer5.fgodinho.com/tls:/etc/hyperledger/fabric/tls
        - peer5.fgodinho.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
