# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.consensus.com:
    container_name: orderer0.consensus.com
    extends:
      file: orderer-base.yaml
      service: orderer-base
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer0.consensus.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer0.consensus.com/tls/:/var/hyperledger/orderer/tls
    - orderer0.consensus.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer1.consensus.com:
    container_name: orderer1.consensus.com
    extends:
      file: orderer-base.yaml
      service: orderer-base
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer1.consensus.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/consensus.com/orderers/orderer1.consensus.com/tls/:/var/hyperledger/orderer/tls
    - orderer1.consensus.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050


  peer0.blockchain-a.com:
    container_name: peer0.blockchain-a.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-a.com
      - CORE_PEER_ADDRESS=peer0.blockchain-a.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-a.com:7051
      - CORE_PEER_LOCALMSPID=PeersAMSP
      - THRESH_SIG_KEY_SHARE=AAAAAQAAAJAMVssN0DYN8YCDQI2zBEPNgDypiq+xRCpQS4dISjzpN2xa8mUBshUgeKl6zHIJpRancLbiFXoh6i/bMC5iRRqsVXh6od11NWBMx6lhq4QCjGM7GEiNghkEoBL5pF6Qlnwy2Oh0nOyu7n/n9c/3YaABAWVdldmPWWLgoFFgMeL+2B8K0xhCqJ6WjFC2VLCQr3QAAACAXJAPiQQVmP1Vcbkg9jNzylOh6TSqvgmkP/Ywql9of9waEBg6EydMoFqiZUsFAq5GJemP8ztyNNdNELCSStNzaMcr198Yz8IRPKjuF2VHQqnj08sKvuWEvgeuyLjJV+u7OScZM8wmyb74usfVSE/6WC3VnjsLQC1btDxGjBNkfq0AAAACAtAAAACARi7NSP/svwt9K6vkuJOKgjdfe0UDFc3qGX4b+uTtkWytOC9GAlRV7YCSeY0YZg5IBfzvf9nuEiL55gxqiDk/9O5G0T1a6bLMxIPsK6tML3KVzRwc4kA4w6DraQAIqVXGhbB/QjvHVqFuATCT+PPpWGVNFsDwjtH3EcQfLuXpie0AAACAMl3/2LGK3BmEzEQoWc+ejD4xLPuwo7KpLkAdjl5eIpKN1WNj4GIH/oQqBG3+NmqG9HlqBsNl0zrVk6n3CJZcaSJm2qI4tfKSQG6h4E/E6Q3Vtc+1TdGRXftLBBSD0l//F3p+iYXprZRlOGGkopJ02wPbSg+unFP9cpLwqMJOWmM=
      - THRESH_SIG_GROUP_KEY=AAAABQAAAAYAAAADAQABAAAAgFyQD4kEFZj9VXG5IPYzc8pToek0qr4JpD/2MKpfaH/cGhAYOhMnTKBaomVLBQKuRiXpj/M7cjTXTRCwkkrTc2jHK9ffGM/CETyo7hdlR0Kp49PLCr7lhL4Hrsi4yVfruzknGTPMJsm++LrH1UhP+lgt1Z47C0AtW7Q8RowTZH6t
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-a.com/peers/peer0.blockchain-a.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-a.com/peers/peer0.blockchain-a.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-a.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.blockchain-b.com:
    container_name: peer0.blockchain-b.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-b.com
      - CORE_PEER_ADDRESS=peer0.blockchain-b.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-b.com:7051
      - CORE_PEER_LOCALMSPID=PeersBMSP
      - THRESH_SIG_KEY_SHARE=AAAAAgAAAJBRJR/v8h80NXOuvlot7e3rPi15y7wM1Z5OgAvzgybrjMvE4wZ0kziD9++Ui8rrGrOJw5/nOp1zjXO9AfBT6vwNXjDeTxMH+IpJH4GdFTwC7uUqk3kWi4tWZEN5Jn9x37uXybXfKuh6IoNTtQvb4/irzs7r5ncc5Y02X7CxPE3CSt0jI8RqbsL6CopIhcKS5vsAAACAXJAPiQQVmP1Vcbkg9jNzylOh6TSqvgmkP/Ywql9of9waEBg6EydMoFqiZUsFAq5GJemP8ztyNNdNELCSStNzaMcr198Yz8IRPKjuF2VHQqnj08sKvuWEvgeuyLjJV+u7OScZM8wmyb74usfVSE/6WC3VnjsLQC1btDxGjBNkfq0AAAACAtAAAACACZxCadnjjUrhB8Gvu77ubnHyapUDto6x1dGMW/5Avz3aFyhJoq7BDYrmrDNkf55+I9e+CjTSYMbNM+40X+IvOMte0fxbU817w6xJa95DnsN5UqcDgVoOqXPcQtQB3lUlHiWxK1FupjnevVXsAtT7ek1V+rMpYZCwlSdnQ5ATCAgAAACAQBU19PCctNEj2iUk77WC7sWe7yl/VFE9qrTuDB/uW5GKsOvxjD7KEBawtm0wpeLK1hrwUqwUvfPa+oWwLMhjYhsTVQwnKAc0P2GpyqNLzMhtodF4grbPeZjJDDf0u5acr5Lwpr0/WuyDklCwA/mOyW0jgr45nBtOgu1aKoBv/G8=
      - THRESH_SIG_GROUP_KEY=AAAABQAAAAYAAAADAQABAAAAgFyQD4kEFZj9VXG5IPYzc8pToek0qr4JpD/2MKpfaH/cGhAYOhMnTKBaomVLBQKuRiXpj/M7cjTXTRCwkkrTc2jHK9ffGM/CETyo7hdlR0Kp49PLCr7lhL4Hrsi4yVfruzknGTPMJsm++LrH1UhP+lgt1Z47C0AtW7Q8RowTZH6t
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-b.com/peers/peer0.blockchain-b.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-b.com/peers/peer0.blockchain-b.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-b.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.blockchain-c.com:
    container_name: peer0.blockchain-c.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-c.com
      - CORE_PEER_ADDRESS=peer0.blockchain-c.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-c.com:7051
      - CORE_PEER_LOCALMSPID=PeersCMSP
      - THRESH_SIG_KEY_SHARE=AAAAAwAAAJAo8Mb8TZ0ztOH3UI7iJvRAJSFlKooADuF9P67e+ozIx8+GqJsAO5LmE8f3CD0A4eRCUFr/CxZb0Pgw0IhiW+dWMME51LaHBI1+x/2Nz9+LznYtCF4z0yfGod2YDbb9w7uhk1hxCoPAYTdPxQnxAolXVb+vy8n8kLSVGEDpQoHoacgxISaLM4t3dy8n0rEuMboAAACAXJAPiQQVmP1Vcbkg9jNzylOh6TSqvgmkP/Ywql9of9waEBg6EydMoFqiZUsFAq5GJemP8ztyNNdNELCSStNzaMcr198Yz8IRPKjuF2VHQqnj08sKvuWEvgeuyLjJV+u7OScZM8wmyb74usfVSE/6WC3VnjsLQC1btDxGjBNkfq0AAAACAtAAAACAQG2t27SnhePJ1P2WRTE0gV4WbEJsLMGX0zAwa7cH8iVlY9Z8iLcA7sVcqE24XR14pSN74mgzkLz5hYr7pWtnXiBqk8JG4U0v6B5Vfe8ztcsMHzN2htIf1XgycjprmSy9hCRdyQ3rV8zq6M3zE1aMy9aNK+CxyJcZEv7t2FsfcUIAAACAODUgTeIhkbnCPkAjEDuEBd3H36YwJh2C9hvowItudSOJTVgtKRK7PqG1XMB0T7d18dI2Ay/JCm9Jz0OhTm17F8NGnFi2STBRBzUw0W1jY+1/U9olgdi6JQtMwGyK45A+KE/FBP1JYuWiqqgPFWqTZl7aj+57QWaj/NAZc5xfl/U=
      - THRESH_SIG_GROUP_KEY=AAAABQAAAAYAAAADAQABAAAAgFyQD4kEFZj9VXG5IPYzc8pToek0qr4JpD/2MKpfaH/cGhAYOhMnTKBaomVLBQKuRiXpj/M7cjTXTRCwkkrTc2jHK9ffGM/CETyo7hdlR0Kp49PLCr7lhL4Hrsi4yVfruzknGTPMJsm++LrH1UhP+lgt1Z47C0AtW7Q8RowTZH6t
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-c.com/peers/peer0.blockchain-c.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-c.com/peers/peer0.blockchain-c.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-c.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.blockchain-d.com:
    container_name: peer0.blockchain-d.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-d.com
      - CORE_PEER_ADDRESS=peer0.blockchain-d.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-d.com:7051
      - CORE_PEER_LOCALMSPID=PeersDMSP
      - THRESH_SIG_KEY_SHARE=AAAABAAAAJAtNeSFaop1N/bMqnMJNnbsnxFpe6B8HwqWOTHO93jomIw/uB5g8QPGWUB9gUFy9KiPPn7Tc+R4zBK8dgyP0U2SIdHqjZLIka0M8izNrxZieA0kktn5dvIVxM9hspjpRGSy/gvlwaj3gFnnG21fbKQLl8QSiPNhRhjouJhLGeZ+NJSdf6mascCsRW5CTMXWursAAACAXJAPiQQVmP1Vcbkg9jNzylOh6TSqvgmkP/Ywql9of9waEBg6EydMoFqiZUsFAq5GJemP8ztyNNdNELCSStNzaMcr198Yz8IRPKjuF2VHQqnj08sKvuWEvgeuyLjJV+u7OScZM8wmyb74usfVSE/6WC3VnjsLQC1btDxGjBNkfq0AAAACAtAAAACAFPEsR9s5q8TV0xYOY5RmVTM6V8qt2IP40QyLkVMEc9odAZA3txeohl8Yh3bjo7wynqwOO5e//JTz27teApOGPufcxcdnB1TXG8tziNeWOyoNCfPCiyjWozqP4dabiFPIxl+p7Hv3+tfv5vIr7YUM2LKlcYfAQZk750ljsZkIszQAAACAGQvZRApOPD/Sg5RDIjD5ipp0WpqmAiVVJ9WzeiqEuJkcgflzE3biM9Hc/e1KE+p6YKz8/tPwKHqpjxQUMFijytzCB69rmg/XyeNDMavDlvF10WIzPZ+S8MEuxioyLiGH3C8J9hotNDtfDZTrxh1FTO+ZNPmYRi2Z4RLLNB+ylr0=
      - THRESH_SIG_GROUP_KEY=AAAABQAAAAYAAAADAQABAAAAgFyQD4kEFZj9VXG5IPYzc8pToek0qr4JpD/2MKpfaH/cGhAYOhMnTKBaomVLBQKuRiXpj/M7cjTXTRCwkkrTc2jHK9ffGM/CETyo7hdlR0Kp49PLCr7lhL4Hrsi4yVfruzknGTPMJsm++LrH1UhP+lgt1Z47C0AtW7Q8RowTZH6t
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-d.com/peers/peer0.blockchain-d.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-d.com/peers/peer0.blockchain-d.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-d.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053



  peer0.blockchain-e.com:
    container_name: peer0.blockchain-e.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-e.com
      - CORE_PEER_ADDRESS=peer0.blockchain-e.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-e.com:7051
      - CORE_PEER_LOCALMSPID=PeersEMSP
      - THRESH_SIG_KEY_SHARE=AAAABQAAAJAnc0BaC84Jfrk+90JNpae3zeEhlcAiWOWSDtQ6+2mrqKRK2bzDbr3lfwYihSEADFb/aV4Bvks4/3MiloItQ3rt147g121pfQDjwrzGWipWpE8xgcMZ2erJGTcsiVzNqx4/3JUW+xb9HDuJtxi8bwfPBjpODWStN2zroA0hbgWT/7zDEaSxUy8n89tmlQszvZ8AAACAXJAPiQQVmP1Vcbkg9jNzylOh6TSqvgmkP/Ywql9of9waEBg6EydMoFqiZUsFAq5GJemP8ztyNNdNELCSStNzaMcr198Yz8IRPKjuF2VHQqnj08sKvuWEvgeuyLjJV+u7OScZM8wmyb74usfVSE/6WC3VnjsLQC1btDxGjBNkfq0AAAACAtAAAACAFZLQh8uFes11A4JEB9RkGzFpmOhLAZ1/BbcxK3uyMPU5dkIb/p2H4bT4OZFMOEPH2ltp1OQlT9hTT0MoxglURTnjBKqYNEzpVKRhiquQUOLiPEQP//sVAj9l4eQXf9iH345bkN9oFp4BLcwt8PbYnjNLQSxLRTXw1yVnInW8b84AAACAFmlmg3/lwcQH+3wZGpQp7YREnsCchsI7tACFUBjDYXkCl6difpcao7/0ZF1Mc5oVXrzsc2qEuqAdmVWHzSPtUVaK7BzLcwA0U+bnbfNYbhwQdMd6jqpe3dPOj5UKkYdOLQQt6eEAH1LkuY9LL2NxkCLF2v9mYwMivarEJj/h90s=
      - THRESH_SIG_GROUP_KEY=AAAABQAAAAYAAAADAQABAAAAgFyQD4kEFZj9VXG5IPYzc8pToek0qr4JpD/2MKpfaH/cGhAYOhMnTKBaomVLBQKuRiXpj/M7cjTXTRCwkkrTc2jHK9ffGM/CETyo7hdlR0Kp49PLCr7lhL4Hrsi4yVfruzknGTPMJsm++LrH1UhP+lgt1Z47C0AtW7Q8RowTZH6t
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-e.com/peers/peer0.blockchain-e.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-e.com/peers/peer0.blockchain-e.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-e.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer0.blockchain-f.com:
    container_name: peer0.blockchain-f.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.blockchain-f.com
      - CORE_PEER_ADDRESS=peer0.blockchain-f.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.blockchain-f.com:7051
      - CORE_PEER_LOCALMSPID=PeersFMSP
      - THRESH_SIG_KEY_SHARE=AAAABgAAAJAi7XOuZ/4xJsQiUzNxaSpLEJ/kCPDMcD9lRPkKsWt9kWYcM4AGugtycMektPHPzcxHJybmbfk23IRcsz8ej30ycm02vgAlFvRMMTP+gzK7TOToH0sXTQQ3pBlqQcOI0VlZ6XidiLfv5O1mf0CaxqAZ/Mqku+ybd5LBdxOzYS5DV+4kVpLmiGfVY2NRT1/MER8AAACAXJAPiQQVmP1Vcbkg9jNzylOh6TSqvgmkP/Ywql9of9waEBg6EydMoFqiZUsFAq5GJemP8ztyNNdNELCSStNzaMcr198Yz8IRPKjuF2VHQqnj08sKvuWEvgeuyLjJV+u7OScZM8wmyb74usfVSE/6WC3VnjsLQC1btDxGjBNkfq0AAAACAtAAAACAJxpMhKYCx8+EzlCY+s+SazXZzNHD2fh6qEVFvNrFgXzKfassi8Xq0kHYaF9i22iTaSfcUgpELtcDnnMhLKlHVv4djC2KjAKZXIDpR3UnwB3P6MSqGSo8u3ZKX/gEwBngll/04WAhmqZ439tEZ6Jh83UZGDB6JLDbmk7BMm4bKfMAAACAONouetK5T42RfTcLpukd8SmIn4D7c3bERj2CCwbBg4lEGFRgsNgKSBtyIZFBZN5fF5409Zv3n7xS4r9WFIV45ldZyIxOdqT3+J92nhDttJZJ6fpVo5VjT722xixg0jFU6cUK6M/5PixcCC914wN9duWLFw2pQ8Hcc+OgxO6Y9TA=
      - THRESH_SIG_GROUP_KEY=AAAABQAAAAYAAAADAQABAAAAgFyQD4kEFZj9VXG5IPYzc8pToek0qr4JpD/2MKpfaH/cGhAYOhMnTKBaomVLBQKuRiXpj/M7cjTXTRCwkkrTc2jHK9ffGM/CETyo7hdlR0Kp49PLCr7lhL4Hrsi4yVfruzknGTPMJsm++LrH1UhP+lgt1Z47C0AtW7Q8RowTZH6t
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/blockchain-f.com/peers/peer0.blockchain-f.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/blockchain-f.com/peers/peer0.blockchain-f.com/tls:/etc/hyperledger/fabric/tls
        - peer0.blockchain-f.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
