# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  bft-replica:
    image: fgodinho/gassy-octopus
    volumes:
        - /var/run/:/host/var/run/
    ports:
      - '11000'
