# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  bft-replica:
    image: fgodinho/gassy-octopus
    environment:
      - BFTSMART_ORDERER_MSPID=OrdererMSP,PeersAMSP,PeersBMSP,PeersCMSP,PeersDMSP,PeersEMSP,PeersFMSP,PeersGMSP,PeersHMSP,PeersIMSP, PeersJMSP,PeersKMSP,PeersLMSP,PeersMMSP,PeersNMSP,PeersOMSP,PeersPMSP,PeersQMSP,PeersRMSP,PeersSMSP,PeersTMSP,PeersUMSP,PeersVMSP,PeersWMSP,PeersXMSP,PeersYMSP,PeersZMSP,P33rsAMSP,P33rsBMSP,P33rsCMSP,P33rsDMSP,P33rsEMSP,P33rsFMSP,P33rsGMSP,P33rsHMSP,P33rsIMSP,P33rsJMSP,P33rsKMSP,P33rsLMSP,P33rsMMSP,P33rsNMSP,P33rsOMSP,P33rsPMSP,P33rsQMSP,P33rsRMSP,P33rsSMSP,P33rsTMSP,P33rsUMSP,P33rsVMSP,P33rsWMSP,P33rsXMSP
      - BFTSMART_REPLICA_CERTIFICATE=/opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart/config/sampleconfig/signcerts/peer.pem
      - BFTSMART_REPLICA_PRIVKEY=/opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart/config/sampleconfig/keystore/key.pem
      - BFTSMART_PARELLELISM=10
      - BFTSMART_BLOCKS_PER_THREAD=10000
      - BFTSMART_RECEIVERS=1000,2000,3000,4000
    volumes:
      - ../crypto-config/bftsmart/keystore:/opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart/config/sampleconfig/keystore
      - ../crypto-config/bftsmart/signcerts:/opt/gopath/src/github.com/hyperledger/fabric/hyperledger-bftsmart/config/sampleconfig/signcerts
    ports:
      - '11000'
